const initState = {
    products: [
        {id: 1, name: 'PCCOOLER Halo FRGB CPU Cooling PWM Single Fan 120mm', image: '1.jpg', price: 20, discount: 2, discountPrice: 20  - 2 / 100 * 20, quantity: 1, desc: "The silent fans adopt wolf claw bionic design helps wind diversion to increase air convection efficiency and greatly improve heat dissipation. Stable operation and reduce noise. The intelligent temperature control mute module controls the speed at 1000~2000±10% RPM.Monochrome glow, monochrome change and rainbow effect.The fan is equipped with 8 ARGB LED beads, 6 colors and 10 light effect modes. The fan frame is fixed on both sides with 8 pieces of shock absorbing rubber pads. "},
        {id: 2, name: 'Xiaomi Mi Band 4 XMSH07HM Touch Bluetooth Smart Watch Black (Chinese Version)', image: '2.jpg', price: 30, discount: 5, discountPrice: 30  - 5 / 100 * 30, quantity: 1, desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Explicabo aspernatur, quo nostrum natus dolor obcaecati reprehenderit reiciendis, repellat omnis voluptates et, dolorem maxime iure sapiente laboriosam quia! Aliquam, vel soluta?"},
        {id: 3, name: 'Mi Power Bank 3 30000mAh 18W Quick Charger Type-C', image: '3.jpg', price: 15, discount: 3, discountPrice: 15  - 3 / 100 * 15, quantity: 1, desc: "Smart compatible with different brands of mobile phones, tablets, to meet the needs of many people such as backpackers, couriers, photographers, outdoor anchors and so on."},
        {id: 4, name: 'MacBook Pro 8Gb 512GB With M1 Chip', image: '4.jpg', price: 50, discount: 4, discountPrice: 50  - 4 / 100 * 50, quantity: 1, desc: "About this item Apple-designed M1 chip for a giant leap in CPU, GPU, and machine learning performance Get more done with up to 20 hours of battery life, the longest ever in a Mac 8-core CPU delivers up to 2.8x faster performance to fly through workflows quicker than ever 8-core GPU with up to 5x faster graphics for graphics-intensive apps and games 16-core Neural Engine for advanced machine learning 8GB of unified memory so everything you do is fast and fluid Superfast SSD storage launches apps and opens files in an instant Active cooling system sustains incredible performance 13.3-inch Retina display with 500 nits of brightness for vibrant colors and incredible image detail FaceTime HD camera with advanced image signal processor for clearer, sharper video calls"},
        {id: 5, name: 'Mi AirPOP LIGHT360° fits Anti-Fog Mask', image: '5.jpg', price: 25, discount: 2, discountPrice: 25  - 2 / 100 * 25, quantity: 1, desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Explicabo aspernatur, quo nostrum natus dolor obcaecati reprehenderit reiciendis, repellat omnis voluptates et, dolorem maxime iure sapiente laboriosam quia! Aliquam, vel soluta?"},
        {id: 6, name: 'PCCOOLER Halo 3-in-1 FGRB Kit, 120mm 4Pin PWM Fan-RGB', image: '6.jpg', price: 60, discount: 6, discountPrice: 60  - 6 / 100 * 60, quantity: 1, desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Explicabo aspernatur, quo nostrum natus dolor obcaecati reprehenderit reiciendis, repellat omnis voluptates et, dolorem maxime iure sapiente laboriosam quia! Aliquam, vel soluta?"},
        {id: 7, name: 'Finger Pulse Oximeter', image: '7.jpg', price: 35, discount: 2, discountPrice: 35  - 2 / 100 * 35, quantity: 1, desc: "Integrate blood oxygen probe and process display module into one The product is small in size, light in weight and easy to carry. The product is easy to use and has low power consumption Blood oxygen saturation value display, pulse rate value, bar graph display, pulse waveform display, battery power indicator Can change the display mode 4 directions change Automatic shutdown function: In the state of the measurement interface, the measured finger is automatically turned off within 5s after being disconnected."},
        {id: 8, name: 'MacBook Pro 4Gb 512GB With M1 Chip', image: '8.jpg', price: 80, discount: 7, discountPrice: 80  - 7 / 100 * 80, quantity: 1, desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Explicabo aspernatur, quo nostrum natus dolor obcaecati reprehenderit reiciendis, repellat omnis voluptates et, dolores maxime iure sapiente laboriosam quia! Aliquam, vel soluta?"},
        {id: 9, name: 'MagSafe Charger Wireless Charger', image: '9.jpg', price: 95, discount: 4, discountPrice: 95  - 4 / 100 * 95, quantity: 1, desc: "The MagSafe Charger makes wireless charging a snap. The perfectly aligned magnets attach to your iPhone 12 or iPhone 12 Pro and provide faster wireless charging up to 15W.The MagSafe Charger maintains compatibility with Qi charging, so it can be used to wirelessed charge your iPhone 8 or later, as well as AirPods models with a wireless charging case, as you would with any Qi-certified charger."},        
        {id: 10, name: '3M 9042V Respirator Activated Carbon Masks with Valve(1Pc)', image: '10.jpg', price: 120, discount: 3, discountPrice: 120  - 3 / 100 * 120, quantity: 1, desc: "Adjustable noseclip, soft inner shell, smooth against face Spacious and durable Ideal for mechanically generated particles, nuisance level of organic vapours and agricultural type chemicals with low vapour pressure, spraying pesticide, herbicide and fungicide Function: dustproof, anti-virus, anti-odor; breathing resistance is small, comfortable to wear; breathable, smooth breathing; Filtration rate of not less than 95%"},
        {id: 11, name: 'Transcend 32GB Micro SD UHS-I U1-Class-10-Memory Card with Adapter (TS32GUSD300S-A)', image: '11.jpg', price: 120, discount: 3, discountPrice: 120  - 3 / 100 * 120, quantity: 1, desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Explicabo aspernatur, quo nostrum natus dolor obcaecati reprehenderit reiciendis, repellat omnis voluptates et, dolorem maxime iure sapiente laboriosam quia! Aliquam, vel soluta?"},
        {id: 12, name: 'Mi Premium Liquid Silicone Case for Redmi K20 series Black', image: '12.jpg', price: 120, discount: 3, discountPrice: 120  - 3 / 100 * 120, quantity: 1, desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Explicabo aspernatur, quo nostrum natus dolor obcaecati reprehenderit reiciendis, repellat omnis voluptates et, dolorem maxime iure sapiente laboriosam quia! Aliquam, vel soluta?"},
        {id: 13, name: 'Mopoer Dash Charge 10000mAh Power Bank', image: '13.png', price: 120, discount: 3, discountPrice: 120  - 3 / 100 * 120, quantity: 1, desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Explicabo aspernatur, quo nostrum natus dolor obcaecati reprehenderit reiciendis, repellat omnis voluptates et, dolorem maxime iure sapiente laboriosam quia! Aliquam, vel soluta?"},
        {id: 14, name: 'Imilab KW66 Screen Protectors', image: '14.jpg', price: 120, discount: 3, discountPrice: 120  - 3 / 100 * 120, quantity: 1, desc: "Designed for Imilab KW66 High definition, high light transmission Electroplated oil layer, long term anti fingerprint Explosion proof, scratch proof, screen protection, sensitive touch Integrated hot bending process, no warping, and no ash feeding."},
        {id: 15, name: 'Wrist Strap for Xiaomi Mi Band 5', image: '15.jpg', price: 120, discount: 3, discountPrice: 120  - 3 / 100 * 120, quantity: 1, desc: "A nice wrist strap replacement to color your bracelet.Soft and tough, comfortable to wear.Breathability Sweatproof Anti-lost Design.This item is only a wrist strap, device not included."},
        {id: 16, name: 'Apple Said to Plan Redesigned AirPods for 2021', image: '16.jpg', price: 120, discount: 3, discountPrice: 120  - 3 / 100 * 120, quantity: 1, desc: "The new base AirPods will mark the first update to the product since March 2019 and will add a new design that mostly mirrors that of the AirPods Pro. The earbuds will come with a new case and shorter stems poking out of the bottom of each one. "}       

    ],
    product: {}
}
const ProductsReducer = (state = initState, action) => {
    switch(action.type){
        case "PRODUCT": 
        return {...state, product: state.products.find(product => product.id === parseInt(action.id))}
        default: 
        return state;
    }
}
export default ProductsReducer;